# D210 - Representation and Reporting Performance Assessment Task 1
Aidan Soares, 012042436, Western Governors University

### A1: Datasets
For this performance assessment, I am doing a comparative analysis for customer demographics and retention within the telecommunications industry using data for two telecommunications companies. 

Dataset 1: I have primarily selected WGU's churn dataset, a dataset for a telecom company that provides internet and mobile services across the United States. The dataset contains a given month's information on 10,000 customers including customer age, tenure, income, service package selection, payment information, and churn status. Throughout the assessment I will refer to this dataset as WGU Telecom Co. [This dataset can be found here](https://access.wgu.edu/ASP3/aap/content/k8gj49f8sichedufutms.html).

Dataset 2: For comparison, I have chosen to select a dataset that closely mirrors the information found within the WGU churn dataset. This dataset was sourced from Kaggle, and contains information on 7043 customers within a telecommunications company based in California. Said information is much like WGU Telecom Co.'s with similar customer information, for the period of Q3. [This dataset can be found here](https://www.kaggle.com/datasets/blastchar/telco-customer-churn) (Kaggle, 2018).

My Tableau story can be found here: https://public.tableau.com/views/PerformanceAssessmentStory/D210Story?:language=en-US&publish=yes&:sid=&:display_count=n&:origin=viz_share_link

**Data Cleaning**

While not required for this performance assessment, I wanted to clean my datasets and concatenate them into one single csv for more efficiency when I import it into Tableau. I want to ensure that are no null or duplicate values, I also want to remove columns that do not exist in both datasets to limit the information only to comparative values, and I will change the column titles to match pandas standard naming conventions, so that concatenation will not result in extra unnecessary columns being created in my combined csv dataset.

In [1]:
#importing necessary libraries
import pandas as pd
import numpy as np

#importing data from csvs into dataframes, indexing on order number if it exists
WGU_df = pd.read_csv('churn_clean.csv', index_col=0)
kaggle_df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [2]:
#printing info to identify any null values/duplicates for the WGU dataset
print(WGU_df.info())
print(WGU_df.duplicated().value_counts())
WGU_df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 1 to 10000
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_id           10000 non-null  object
 1   Interaction           10000 non-null  object
 2   UID                   10000 non-null  object
 3   City                  10000 non-null  object
 4   State                 10000 non-null  object
 5   County                10000 non-null  object
 6   Zip                   10000 non-null  int64
 7   Lat                   10000 non-null  float64
 8   Lng                   10000 non-null  float64
 9   Population            10000 non-null  int64
 10  Area                  10000 non-null  object
 11  TimeZone              10000 non-null  object
 12  Job                   10000 non-null  object
 13  Children              10000 non-null  int64
 14  Age                   10000 non-null  int64
 15  Income                10000 non-null  float64
 16  Marital               10000 non-null  object
 17  Gender                10000 non-null  object
 18  Churn                 10000 non-null  object
 19  Outage_sec_perweek    10000 non-null  float64
 20  Email                 10000 non-null  int64
 21  Contacts              10000 non-null  int64
 22  Yearly_equip_failure  10000 non-null  int64
 23  Techie                10000 non-null  object
 24  Contract              10000 non-null  object
 25  Port_modem            10000 non-null  object
 26  Tablet                10000 non-null  object
 27  InternetService       10000 non-null  object
 28  Phone                 10000 non-null  object
 29  Multiple              10000 non-null  object
 30  OnlineSecurity        10000 non-null  object
 31  OnlineBackup          10000 non-null  object
 32  DeviceProtection      10000 non-null  object
 33  TechSupport           10000 non-null  object
 34  StreamingTV           10000 non-null  object
 35  StreamingMovies       10000 non-null  object
 36  PaperlessBilling      10000 non-null  object
 37  PaymentMethod         10000 non-null  object
 38  Tenure                10000 non-null  float64
 39  MonthlyCharge         10000 non-null  float64
 40  Bandwidth_GB_Year     10000 non-null  float64
 41  Item1                 10000 non-null  int64
 42  Item2                 10000 non-null  int64
 43  Item3                 10000 non-null  int64
 44  Item4                 10000 non-null  int64
 45  Item5                 10000 non-null  int64
 46  Item6                 10000 non-null  int64
 47  Item7                 10000 non-null  int64
 48  Item8                 10000 non-null  int64
dtypes: float64(7), int64(15), object(27)
memory usage: 3.8+ MB
None
False    10000
dtype: int64

,Customer_id,Interaction,UID,City,State,County,Zip,Lat,Lng,Population,...,MonthlyCharge,Bandwidth_GB_Year,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8
CaseOrder,,,,,,,,,,,,,,,,,,,,,
1,K409198,aa90260b-4141-4a24-8e36-b04ce1f4f77b,e885b299883d4f9fb18e39c75155d990,Point Baker,AK,Prince of Wales-Hyder,99927,56.25100,-133.37571,38,...,172.455519,904.536110,5,5,5,3,4,4,3,4
2,S120509,fb76459f-c047-4a9d-8af9-e0f7d4ac2524,f2de8bef964785f41a2959829830fb8a,West Branch,MI,Ogemaw,48661,44.32893,-84.24080,10446,...,242.632554,800.982766,3,4,3,3,4,3,4,4
3,K191035,344d114c-3736-4be5-98f7-c72c281e2d35,f1784cfa9f6d92ae816197eb175d3c71,Yamhill,OR,Yamhill,97148,45.35589,-123.24657,3735,...,159.947583,2054.706961,4,4,2,4,4,3,3,3
4,D90850,abfa2b40-2d43-4994-b15a-989b8c79e311,dc8a365077241bb5cd5ccd305136b05e,Del Mar,CA,San Diego,92014,32.96687,-117.24798,13863,...,119.956840,2164.579412,4,4,4,2,5,4,3,3
5,K662701,68a861fd-0d20-4e51-a587-8a90407ee574,aabb64a116e83fdc4befc1fbab1663f9,Needville,TX,Fort Bend,77461,29.38012,-95.80673,11352,...,149.948316,271.493436,4,4,4,3,4,4,4,5

In [3]:
#removing the irrelevant columns from the WGU churn dataset
WGU_df.drop(columns=["Interaction", "UID", "City", "State", "County", "Zip", "Lat", 
                      "Lng", "Population", "Area", "TimeZone", "Job", "Age", "Income", 
                      "Outage_sec_perweek", "Email", "Contacts", "Yearly_equip_failure",
                      "Techie", "Port_modem", "Tablet", "Bandwidth_GB_Year", "Item1", "Item2",
                      "Item3", "Item4", "Item5", "Item6", "Item7", "Item8"], inplace=True)

#re-expressing all column names to be pandas standard naming convention
WGU_df.rename(columns= {"Customer_id":"customer_id", "Children":"children", "Marital":"married", 
                        "Gender":"gender", "Churn":"churn", "Contract":"contract", "InternetService":"internet_service",
                        "Phone":"phone", "Multiple":"multiple_phone", "OnlineSecurity":"online_security",
                        "OnlineBackup":"online_backup", "DeviceProtection":"device_protection",
                        "TechSupport":"tech_support", "StreamingTV":"streaming_tv", "StreamingMovies":"streaming_movies",
                        "PaperlessBilling":"paperless_billing", "PaymentMethod":"payment_method", "Tenure":"tenure", 
                        "MonthlyCharge":"monthly_charge"}, inplace=True)

#re-expressing children to binary status (Stackoverflow, 2019)
WGU_df["children"] = np.where(WGU_df["children"]>=1, "Yes", "No")

#re-expressing married status to binary with dictionary
m_dict = {"married": 
          {"Married":"Yes", "Widowed":"No",
           "Separated":"No", "Single":"No",
           "Divorced":"No", "Never Married":"No"}}
WGU_df.replace(m_dict, inplace=True)

#re-expressing "Two Year" in contract to "Two year" for consistency
WGU_df['contract'].replace("Two Year", "Two year", inplace=True)

#re-expressing payment method into 3 categories: Automatic, Mailed Check, Electronic Check
p_dict = {"payment_method": 
          {"Credit Card (automatic)":"Automatic", 
           "Bank Transfer(automatic)":"Automatic"}}
WGU_df.replace(p_dict, inplace=True)

#rounding the tenure and monthly charge columns to match the data format of the kaggle dataset
WGU_df["monthly_charge"] = WGU_df["monthly_charge"].round(2)
WGU_df["tenure"] = WGU_df["tenure"].round(0)

#adding an additional column to indicate the source of data (WGU)
WGU_df["source"] = "WGU"

WGU_df.head()

,customer_id,children,married,gender,churn,contract,internet_service,phone,multiple_phone,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,paperless_billing,payment_method,tenure,monthly_charge,source
CaseOrder,,,,,,,,,,,,,,,,,,,,
1,K409198,No,No,Male,No,One year,Fiber Optic,Yes,No,Yes,Yes,No,No,No,Yes,Yes,Automatic,7.0,172.46,WGU
2,S120509,Yes,Yes,Female,Yes,Month-to-month,Fiber Optic,Yes,Yes,Yes,No,No,No,Yes,Yes,Yes,Automatic,1.0,242.63,WGU
3,K191035,Yes,No,Female,No,Two year,DSL,Yes,Yes,No,No,No,No,No,Yes,Yes,Automatic,16.0,159.95,WGU
4,D90850,Yes,Yes,Male,No,Two year,DSL,Yes,No,Yes,No,No,No,Yes,No,Yes,Mailed Check,17.0,119.96,WGU
5,K662701,No,No,Male,Yes,Month-to-month,Fiber Optic,No,No,No,No,No,Yes,Yes,No,No,Mailed Check,2.0,149.95,WGU

In [4]:
#printing info to identify any null values/duplicates for the kaggle dataset
print(kaggle_df.info())
print(kaggle_df.duplicated().value_counts())
kaggle_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None
False    7043
dtype: int64

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
#removing the irrelevant columns from the kaggle churn dataset
kaggle_df.drop(columns=["SeniorCitizen", "TotalCharges"], inplace=True)

#re-expressing all column names to be pandas standard naming convention
kaggle_df.rename(columns= {"customerID":"customer_id", "Partner":"married", 
                        "Dependents":"children", "Churn":"churn", "Contract":"contract", "InternetService":"internet_service",
                        "PhoneService":"phone", "MultipleLines":"multiple_phone", "OnlineSecurity":"online_security",
                        "OnlineBackup":"online_backup", "DeviceProtection":"device_protection",
                        "TechSupport":"tech_support", "StreamingTV":"streaming_tv", "StreamingMovies":"streaming_movies",
                        "PaperlessBilling":"paperless_billing", "PaymentMethod":"payment_method", 
                        "MonthlyCharges":"monthly_charge"}, inplace=True)

#re-expressing multiple lines to binary with dictionary
ml_dict = {"multiple_phone": 
          {"No phone service":"No"}}
kaggle_df.replace(ml_dict, inplace=True)

#re-expressing payment method into 3 categories: Automatic, Mailed Check, Electronic Check
pm_dict = {"payment_method": 
          {"Credit card (automatic)":"Automatic", 
           "Bank transfer (automatic)":"Automatic",
           "Mailed check":"Mailed Check", "Electronic check":"Electronic Check"}}
kaggle_df.replace(pm_dict, inplace=True)

#re-expressing internet service to proper naming convention with dictionary
in_dict = {"internet_service": 
          {"Fiber optic":"Fiber Optic", "No":"None"}}
kaggle_df.replace(in_dict, inplace=True)

#re-expressing "No internet service" to "No" 
kaggle_df.replace("No internet service", "No", inplace=True)


#adding an additional column to indicate the source of data (WGU)
kaggle_df["source"] = "Kaggle"

kaggle_df.head()

,customer_id,gender,married,children,tenure,phone,multiple_phone,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charge,churn,source
0,7590-VHVEG,Female,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic Check,29.85,No,Kaggle
1,5575-GNVDE,Male,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed Check,56.95,No,Kaggle
2,3668-QPYBK,Male,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed Check,53.85,Yes,Kaggle
3,7795-CFOCW,Male,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Automatic,42.30,No,Kaggle
4,9237-HQITU,Female,No,No,2,Yes,No,Fiber Optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic Check,70.70,Yes,Kaggle

In [6]:
#merging both datasets into one for easy import into Tableau
clean_df = pd.concat([WGU_df, kaggle_df], ignore_index=True)
clean_df.head()

,customer_id,children,married,gender,churn,contract,internet_service,phone,multiple_phone,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,paperless_billing,payment_method,tenure,monthly_charge,source
0,K409198,No,No,Male,No,One year,Fiber Optic,Yes,No,Yes,Yes,No,No,No,Yes,Yes,Automatic,7.0,172.46,WGU
1,S120509,Yes,Yes,Female,Yes,Month-to-month,Fiber Optic,Yes,Yes,Yes,No,No,No,Yes,Yes,Yes,Automatic,1.0,242.63,WGU
2,K191035,Yes,No,Female,No,Two year,DSL,Yes,Yes,No,No,No,No,No,Yes,Yes,Automatic,16.0,159.95,WGU
3,D90850,Yes,Yes,Male,No,Two year,DSL,Yes,No,Yes,No,No,No,Yes,No,Yes,Mailed Check,17.0,119.96,WGU
4,K662701,No,No,Male,Yes,Month-to-month,Fiber Optic,No,No,No,No,No,Yes,Yes,No,No,Mailed Check,2.0,149.95,WGU

In [7]:
#exporting dataset into its own csv
clean_df.to_csv("combined_dataset.csv", index=False)

### A2: Dashboard Installation
To access my dashboard, no installation is required. I wanted it to be universally accessible to those without the Tableau program, as such, the only thing required to access the dashboard is this link: https://public.tableau.com/views/PerformanceAssessmentStory/D210Story?:language=en-US&publish=yes&:sid=&:display_count=n&:origin=viz_share_link

It can be accessed from any browser such as google chrome.

Should the user want to install a local version on their own computer, the instructions to install my dashboard are as follows:
1. Go to the [Tableau Public website](https://public.tableau.com/app/discover) through any internet browser
2. Under the Create tab in the upper left corner, select **Download Tableau Desktop Public Edition**, aftre creating or signing into a Tableau account this will download an installation software
3. After running the installation software, Tableau Public will open
4. Within the app, hover over File and click on Open...
5. Select my **Performance Assessment Story.twbx** file
6. If the program prompts you to select an existing dataset please select the **combined_dataset.csv** file provided
7. You will now have access to my dashboards and story. For space and efficiency reasons, I have hidden the individual sheets that contain the visualizations. If you would like to see them, right click on any dashboard in the bar below and select **Unhide All Sheets**


For users that are looking for instructions on how to create my dashboards, the instructions are as follows. Please open a blank document in Tableau public and import the **combined_dataset.csv** file provided:

**Creating Worksheets** (generate by clicking the New Worksheet button at the bottom tab, do this after every step)
1. Payment method treemap: drag the Payment Method table from the left side to the Columns area, then drag it again to the Rows area. Right click on the Payment Method in the Rows section and select Measure > Count. On the upper right side of the screen click Show Me and select Treemap.
2. Gender breakdown: drag the Source table to the Columns area, then drag Gender to the Rows area. Right click on the Gender button in the Rows section and select Measure > Count. On the upper right side of the screen click Show Me and select Pie Chart. Drag a Gender table to the Label box in the Marks area and then right click on the resulting Gender table in the Marks area and click Quick Table Calculation > Percentage of Total to add percentages to the visualization.
3. Contract Types bar chart: drag the Contract table to the Columns area, right clicking it and then selecting Measure > Count. Then drag another Contract table to the Rows area. The bar chart will automatically populate as a bar chart. Hold ctrl and drag the CNT(Contract) table from the Columns area to the Label box in the Marks section on the left to add numbers to the chart. 
4. Internet Service bar chart: the same as step 4 but using the Internet Service table instead.
5. Monthly Charge Rates: drag the Monthly Charge table to the Columns area, then drag it again to the Rows area. Right click on the Monthly Charge in the Rows section and select Measure > Count. The bar chart will automatically populate. 
6. Total Churn Rates: drag the Churn table from the left side to the Columns area, then drag it again to the Rows area. Right click on the Churn in the Rows section and select Measure > Count. To add text to the chart drag the Source table to the Labels box in the Marks area. Hold Ctrl and drag the CNT(Churn) table to the Label box, right click on it and select Quick Table Calculation > Percentage of Total to add percentages to the visualization.
7. Tenure Rate per Service Contract: drag the Internet Service table from the left side to the Columns area, then drag Tenure to the Rows area. Right click on the Tenure in the Rows section and select Measure > Average. On the upper right side of the screen click Show Me and select Treemap. Then right click on the visualization and select Filters > Payment Method.
8. Source Filter: drag the Source table from the left side to the Columns area, then drag it again to the Rows area. Right click on the Source in the Column section and select Measure > Count. Then drag the CNT(Source) to the Text box in the Marks area.
9. Tenure assessment stacked chart: drag the Tenure table to the Columns area, then drag it again to the Rows area. Right click on the Tenure in the Rows section and select Measure > Count. Click Show Me on the upper right side and select Area Chart.


**Creating dashboards** (generate by clicking the New Dashboard button at the botton tab, do this after every step)
1. Customer demographic overview: Drag in the Contract Types, Internet Service, Monthly Charge Rates, Payment Method Count, Count of Records, and Gender Breakdown worksheets. Then drag a Text object to the top of the dashboard to insert a Title. Use the dropdown menu on the Gender Breakdown chart and select Filters > Gender. Then do the same with the Monthly Charge Rates chart and select Filters > Action(Source)
2. Customer turnover analysis: Drag in the Tenure Assessment, Tenure Rates, and Total Churn Rates worksheets. Then drag a Text object to the top of the dashboard to insert a Title. Use the dropdown menu on the Tenure Assessment chart and select Filters > Tenure.

### A3: Navigation Instructions
Once you arrive on my story you will be presented with 4 tabs on the top of the screen denoting the different dashboards available to view. By Clicking any of those tabs you will be brought to different pages with different purposes, they are meant to be viewed in order from left to right.

The **Introduction** page is simply an overview of the content of my story, a review of customer retention analysed from the data collected from WGU's Telecom Company, and its competitor; a dataset sourced from Kaggle.

The **Customer Demographics** page contains a high level overview of the user demographics for each telecom company, with visualizations that summarize breakdowns of customer gender, selection of payment method, internet service, contract types, and distribution of monthly charges to customers. There are two included interactive filters within this dashboard: one for gender and one for company datasource. This allows for users to isolate data and information to gain key insights along specific demographics.

The **Retention Analysis** dashboard provides a focus on key performance metrics for the churn status of each telecommunications company. In it, you will find a breakdown of churn proportions among customers within the rolling period found within the dataset, the average tenure rates yielded for each service contract offering, and a stacked chart that visualizes the total number of customers for every tenure length. This dashboard also contains two interactive filters to specific data constraints such as payment method type and tenure length.

The **Recommendations** dashboard gives an overview of the insights resulting from the analysis performed within my story, and recommendations that the WGU Telecom Company can act upon to seek better customer retention.

### B: Storytelling
A panopto video covering my presentation regarding the data can be found here: https://wgu.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=1759ffce-e347-402c-bec9-b16d00386ed0

### C1: Dashboard Alignment
The dashboards within my story serve to grant management a high-level overview of customer and performance data at a comprehensible glance through easy to nagivate visualizations and filters that isolate key data. I have used the churn dataset many times in my past performance assessments but this is the first time I get to compare it against an industry benchmark to assess key metrics as an internal stakeholder would. When constructing the paired dataset, I wanted to make sure there the comparison was being performed as directly as possible, which meant isolating only the shared features between both datasets to reduce bloat and shrink the dataset into directly comparable metrics. In doing so, I have built a dataset that provides exploration of customer demographic structure and has visualizations/filters available for use in comparing key performance metrics so that executive leaders can ascertain industry trends, competitor advantages, and assess current performance to a direct competitor, all in an interactive platform that conveys important insights at a glance.

### C2: Additional Dataset Insights
The variables noted from the external dataset happened to demonstrate much similarity in the product offerings of WGU's churn dataset. Within, I noted that both companies offer the same internet services such as DSL and fiber optic. Additionally, payment processing, contract type, tenure, churn status, as well as extra packages such as device protection and online backup were present as well. Due to the similarity in service offerings, I knew this would be the perfect selection for industry comparison as utilizing a direct competitor allows for assessment of benchmarks in success. Using both of these datasets in conjunction has allowed me to identify insights into common industry norms (such as the proportion of internet type selected), and performance status in comparison to another similar company (such as the ratio between customers churning), which helps in knowing if the WGU Telecom Company performs uniquely from industry standards.

### C3: Decision-Making Support
I have established the **Retention Analysis** dashboard as the page that grants actionable supporting evidence for decision makers. Within, you will find a treemap that demonstrates the highest tenure lengths yielded per service contract offering, showing the internet type with the highest average tenure in the darkest color as DSL, the internet type with the next highest retention is shown in a lighter color as FiberOptic, and so on. This treemap can be utilized by management to identify which internet service they could structure an advertising campaign around to encourage new customers to subscribe to. Another data representation that grants very useful insights into potential retention boosting features would be stacked chart in the Retention Analysis dashboard representing the number of customers at each tenure length, going from 1 month to 72. We can see that both companies' customers follow a relatively similar trend, then at the highest tenure length the graph diverges, showing that the competitor company pulls ahead of WGU Telecom Co. in customers who have 72 months of tenure. Upon utilizing the filter on the right side of the dashboard to isolate the Automatic payment method we immediately see that customers who utilize the Automatic payment type are the cause for this, as this trend does not exist within customers that use Electronic Check and Mailed Check for payment. This allows for management to again identify trends leading to better tenure rates and generate targeted marketing campaigns to encourage subscription with these benchmarks.

### C4: Interactive Controls
My interactive controls consist of various filters that can be used on either of my two visualization dashboards. On the customer demogrpahics tab users can utilize the drop-down menu to filter data to a specific gender, or use the source filter on the right side to isolate data from each telecom company. Additionally in the retention analysis tab I have provided a payment method filter to isolate churn/tenure rates by payment method, and another bar-based tenure length filter, which the user may use to adjust the scale of the tenure assessment chart. Within the tick-box filters I added 'Apply' button that confirms filtering options as an added feature to prevent accidental filtering.

### C5: Accessibility
My dashboards were built with colorblidness accessibility in mind by using charts and visualizations that are primarily focused on shape, such as pie charts, tree maps in varying sizes, bar graphs, and stacked charts so there wouldn't be a heavy reliance on color to distinguish metrics. However, for all visualizations using color I made sure to utilize the 'colorblindness' color palette to make them accessible to people who are colorblind as well.

### C6: Data Representations
The goal of my dashboards is to tell multiple stories of how WGU's Telecom Company compares to another competitor within the industry to assess trends, identify areas of improvement, and determine what the competitor may be doing to achieve higher customer retention. The first area I noticed potential to convey a space for improvement was within the customer demographics tab. Within, I noticed that upon filtering between WGU's telecom dataset and the competitor dataset is that the monthly charge rates differred severely between WGU Telecom and its competitor, while I don't have the domain knowledge to assess the cost-benefit analysis of WGU Telecom having a lower monthly rate than its current amount, it's certainly a data representation that supports looking further at bringing more appealing to customers long-term. Another area that conveys the current churn trends between WGU Telecom and its competitor can be found in the retention analysis tab. In the left of the dashboard, users will see a comparative bar graph displaying the ratio between customers that have churned vs. those that have not within the dataset period. The story I wanted to convey here is that it appears, based on the datasets available for analysis, that the churn ratio present within the data seems to be common within the industry, and that WGU Telecom Co. is not performing at a subpar level since the ratio is the exact same between WGU and its competitor.

### C7: Audience Analysis
For this assessment, I am focusing primarily on a story meant to present value to stakeholders such as internal management and higher level executives with an overview of the whole company. As the information is meant to be viewed at a high level, it is meant for the members of management that are focused on performance indicators, giving them insights on how to focus resources that lead to material impact. Visual representations such as the customer demographics dashboard can give them a quick and easy way to review what the popular selection trends are among current customers. This audience analysis can be adapted on a smaller basis to. Instead of high-level management, this analysis can be done on a divisional basis to focus and divide resources and delegate management to assess performance in their own way, giving middle-level management the freedom to perform the analysis at the ground level and pass that information up the chain instead.

### C8: Universal Access
To ensure that my tableau story can be accessed universally, I have uploaded my story to the Tableau Public platform. This ensures that any user who wishes to view my analysis can do so simply through any internet browser without having to install Tableau or pay for a licensing fee or without having to download a file to a local machine. In addition, as my story is uploaded via browser, mobile users can access it this way as well, making it a story that can be easily accessable through many devices.

### C9: Storytelling
To maintain a strong capitavation on my target audience it was very important that the information I presented had to be very brief and could be understood at a glance. Storytelling works most effectively when I can convey information concisely, so the visualizations I have used within my presentation are tailored to brief bouts of comparative data that can convey its meaning while giving visual reference in a manner that could be understood without significant understanding of technical details. Furthermore, another element of storytelling I have employed for this presentation was to focus on information that was relevant and impactful for the stakeholders. I decided to keep most of my presentation, as well as the ending recommendations, focused on actionable insights that will impact the bottom line; executive management is most concerned with financial impact and improvement, so I kept my analysis focused on this to present only the pertinent data that decision-makers would be most interested in learning to engage the audience.

### D: Sources
B, Michell. (2014, February). *Conditional Replace Pandas*. StackOverflow. https://stackoverflow.com/questions/21608228/conditional-replace-pandas

Blastchar. (2018, February). *Telco Customer Churn*. Kaggle. https://www.kaggle.com/datasets/blastchar/telco-customer-churn